version: '3.8'
 
services:
  flower-app-web:
    image: suwetha07/flowerimage:latest
    container_name: flowerimage
    ports:
      - "3016:3015"
    environment:
      - MONGO_URL=mongodb://mongo:27017/flowerdb
    depends_on:
      - mongo
 
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
 
volumes:
  mongo-data:

 