version: "3.8"

services:
  flower-app-web:
    image: mvnsakash/flower:latest
    container_name: flower-app
    ports:
      - "3016:3015"
    env_file:
      - .env
    environment:
      MONGODB_URI: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin"
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: flower-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"